[version]
source = "vcs"

[build.hooks.vcs]
version-file = "src/simple_sqlite3_orm/_version.py"

[build.targets.sdist]
exclude = ["/.github", "/docs"]

[build.targets.wheel]
only-include = ["src"]
sources = ["src"]
